# Generated by Django 2.0.6 on 2018-08-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='street_address1',
            new_name='street_address_1',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='street_address2',
            new_name='street_address_2',
        ),
    ]
