# Generated by Django 2.0.6 on 2018-08-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20180824_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
