manufacturers = (
    ('GIBSON', 'Gibson'),
    ('T-REX', 'T-Rex'),
    ('SUPRO', 'Supro'),
    ('DBX', 'Dbx'),
    ('DYNACHORD', 'Dynachord'),
    ('MCNALLY', 'Mcnally'),
    ('BOSS', 'Boss'),
    ('CORNELL', 'Cornell'),
    ('NATIONAL', 'National'),
    ('FAITH', 'Faith'),
    ('MAD PROFESSOR', 'Mad Professor'),
    ('ROCKBOX', 'Rockbox'),
    ('TANGLEWOOD', 'Tanglewood'),
    ('RADIAL ENGINEERING', 'Radial Engineering'),
    ('TC ELECTRONIC', 'Tc Electronic'),
    ('SELMER', 'Selmer'),
    ('BARTOLINI', 'Bartolini'),
    ('SEYMOUR DUNCAN', 'Seymour Duncan'),
    ('MAYSON', 'Mayson'),
    ('SOUNDBLOX', 'Soundblox'),
    ('JAMES MEYLER', 'James Meyler'),
    ('65 AMPS', '65 Amps'),
    ('J. ROCKETT', 'J. Rockett'),
    ('TAKAMINE', 'Takamine'),
    ('ATKIN', 'Atkin'),
    ('MARSHALL', 'Marshall'),
    ('EMPRESS', 'Empress'),
    ('HOFNER', 'Hofner'),
    ('DIAMOND', 'Diamond'),
    ('BLACKSTAR', 'Blackstar'),
    ('KEELEY', 'Keeley'),
    ('MI AUDIO', 'Mi Audio'),
    ('CORNERSTONE MUSIC GEAR', 'Cornerstone Music Gear'),
    ('VISUAL SOUND', 'Visual Sound'),
    ('GUILD', 'Guild'),
    ('ROGER MAYER', 'Roger Mayer'),
    ('GRETSCH', 'Gretsch'),
    ('MATAMP', 'Matamp'),
    ('WEEHBO', 'Weehbo'),
    ('GURUS', 'Gurus'),
    ('RICKENBACKER', 'Rickenbacker'),
    ('CARL MARTIN', 'Carl Martin'),
    ('DR. Z', 'Dr. Z'),
    ('CHARVEL', 'Charvel'),
    ('DEAN', 'Dean'),
    ('WEM', 'Wem'),
    ('MXR', 'Mxr'),
    ('LOWDEN', 'Lowden'),
    ('COLLINGS', 'Collings'),
    ('FOXX', 'Foxx'),
    ('XTA ELECTRONICS', 'Xta Electronics'),
    ('WARRIOR', 'Warrior'),
    ('TRAVELER GUITAR', 'Traveler Guitar'),
    ('NASH GUITARS', 'Nash Guitars'),
    ('GIL YARON', 'Gil Yaron'),
    ('MATON', 'Maton'),
    ('WAMPLER', 'Wampler'),
    ('ART & LUTHERIE', 'Art & Lutherie'),
    ('MARTIN', 'Martin'),
    ('MAGUS INNOVATIONS', 'Magus Innovations'),
    ('GEAR MAN DUDE', 'Gear Man Dude'),
    ('L.R. BAGGS', 'L.R. Baggs'),
    ('CHASE BLISS AUDIO', 'Chase Bliss Audio'),
    ('SIGMA', 'Sigma'),
    ('TONE KING', 'Tone King'),
    ('FISHMAN', 'Fishman'),
    ('COLOURSOUND', 'Coloursound'),
    ('BLACK ARTS TONEWORKS', 'Black Arts Toneworks'),
    ('EMERSON CUSTOM', 'Emerson Custom'),
    ('IBANEZ', 'Ibanez'),
    ('JAMES TYLER', 'James Tyler'),
    ('SQUIER', 'Squier'),
    ('ROTOSOUND', 'Rotosound'),
    ('TAYLOR', 'Taylor'),
    ('MAGNATONE', 'Magnatone'),
    ('CORNFORD', 'Cornford'),
    ('EARTHQUAKER DEVICES', 'Earthquaker Devices'),
    ('LOVEPEDAL', 'Lovepedal'),
    ('PRS', 'Prs'),
    ('TUGGI', 'Tuggi'),
    ('DONNER', 'Donner'),
    ('SOLOWAY', 'Soloway'),
    ('BINSON', 'Binson'),
    ('JHS', 'Jhs'),
    ('ESP', 'Esp'),
    ('DUESENBERG', 'Duesenberg'),
    ('B&G GUITARS', 'B&G Guitars'),
    ('AVALON', 'Avalon'),
    ('YAMAHA', 'Yamaha'),
    ('MOOG', 'Moog'),
    ('VOX', 'Vox'),
    ('OVERWATER', 'Overwater'),
    ('FENDER', 'Fender'),
    ('AGUILAR', 'Aguilar'),
    ('OKKO', 'Okko'),
    ('THORPY FX', 'Thorpy Fx'),
    ('MOJO HAND FX', 'Mojo Hand Fx'),
    ('DEVI EVER', 'Devi Ever'),
    ('EHX', 'Ehx'),
    ('SWART', 'Swart'),
    ('WREN AND CUFF', 'Wren And Cuff'),
    ('EPIPHONE', 'Epiphone'),
    ('MOOER', 'Mooer'),
    ('ORANGE', 'Orange'),
    ('MESA', 'Mesa'),
)
    
types = (
    ('PICKUP', 'Pickup'),
    ('BASS', 'Bass'),
    ('ACOUSTIC', 'Acoustic'),
    ('ELECTRIC', 'Electric'),
    ('AUDIO', 'Audio'),
    ('EFFECTS', 'Effects'),
    ('AMPLIFIER', 'Amplifier'),
)