# Generated by Django 2.0.6 on 2018-07-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200)),
                ('about_content', models.TextField()),
                ('address_title', models.CharField(max_length=200)),
                ('address_content', models.TextField()),
                ('contact_title', models.CharField(max_length=200)),
                ('contact_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
