# Generated by Django 2.0.6 on 2018-06-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
