# Generated by Django 2.0.6 on 2018-08-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180824_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(max_length=254, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(max_length=254, upload_to='images'),
        ),
    ]
